name: Build Test - cli:latest

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    strategy:
      fail-fast: false
      matrix:
        app:
          - azureFunctionsApps/DotNetCore_HttpTriggerV3Sample
          - azureFunctionsApps/DotNetCore_HttpTriggerV4Sample
          - azureFunctionsApps/Node_HttpTriggerSample
          - azureFunctionsApps/Python_HttpTriggerSample
          - azureFunctionsApps/TypeScript_HttpTriggerSample
          - DotNetCore/Net5BlazorWasmClientApp
          - DotNetCore/Net5MvcApp
          - DotNetCore/NetCore6BlazorWasmApp
          - DotNetCore/NetCore6PreviewMvcApp
          - DotNetCore/NetCore7PreviewMvcApp
          - DotNetCore/NetCore60IsolatedApp
          - DotNetCore/NetCoreApp30.MvcApp
          - DotNetCore/NetCoreApp31.MvcApp
          - DotNetCore/NetCoreApp50MvcApp
          - nodejs/angular14app
          - nodejs/create-react-app-sample
          - nodejs/helloworld-nuxtjs
          - nodejs/monorepo-lerna-npm
          - nodejs/nextjs-yarn2-example
          - nodejs/NodeAndTypeScriptHelloWorld
          - nodejs/node-mssql
          - nodejs/node-postgres
          - nodejs/vuepress
          - nodejs/webfrontend-yarnlock
          - nodejs/websocket
          - php/exif-example
          - php/gd-example
          - php/mysqli-example
          - php/pgsql-example
          - php/sqlsrv-example
          - php/twig-example
          - php/wordpress-example
          - python/django-app
          - python/flask-app
          - python/http-server-py
          - python/mssqlserver-sample
          - python/postgres-sample
          - python/shapely-flask-app

    steps:
      - uses: actions/checkout@v3
        with:
          repository: microsoft/Oryx

      - name: Build application
        run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app pauldtestacr.azurecr.io/oryx/cli:latest oryx build /app
