name: Test Bullseye SWA support yml

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        NetCore6BlazorWasmApp:
          app: DotNetCore/NetCore6BlazorWasmApp
        NetCore6PreviewMvcApp:
          app: DotNetCore/NetCore6PreviewMvcApp
        NetCore7PreviewMvcApp:
          app: DotNetCore/NetCore7PreviewMvcApp

    steps:
      - uses: actions/checkout@v3
        with:
          repository: microsoft/Oryx

      - name: Build application
        run: docker run --rm --env ORYX_SDK_STORAGE_BASE_URL="https://oryxsdksdev.blob.core.windows.net" -v $(pwd)/tests/SampleApps/$(app):/app mcr.microsoft.com/oryx/build:github-actions-bullseye oryx build /app --debug
