name: Bullseye SWA support testing

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        test:
          app: azureFunctionsApps/DotNetCore_HttpTriggerV3Sample
          versionString: ""
        test:
          app: azureFunctionsApps/DotNetCore_HttpTriggerV4Sample
          versionString: ""
        test:
          app: azureFunctionsApps/Node_HttpTriggerSample
          versionString: ""
        test:
          app: azureFunctionsApps/Python_HttpTriggerSample
          versionString: ""
        test:
          app: azureFunctionsApps/TypeScript_HttpTriggerSample
          versionString: ""
        test:
          app: DotNetCore/NetCore6BlazorWasmApp
          versionString: ""
        test:
          app: DotNetCore/NetCore6PreviewMvcApp
          versionString: ""
        test:
          app: DotNetCore/NetCore7PreviewMvcApp
          versionString: ""
        test:
          app: DotNetCore/NetCore60IsolatedApp
          versionString: ""
        test:
          app: DotNetCore/NetCoreApp31.MvcApp
          versionString: ""
        test:
          app: golang/hello-world
          versionString: ""
        test:
          app: hugo/hugo-sample
          versionString: ""
        test:
          app: java/MavenSimpleJavaApp
          versionString: ""
        test:
          app: nodejs/angular14app
          versionString: ""
        test:
          app: nodejs/create-react-app-sample
          versionString: ""
        test:
          app: nodejs/helloworld-nuxtjs
          versionString: ""
        test:
          app: nodejs/monorepo-lerna-npm
          versionString: ""
        test:
          app: nodejs/nextjs-yarn2-example
          versionString: ""
        test:
          app: nodejs/NodeAndTypeScriptHelloWorld
          versionString: ""
        test:
          app: nodejs/node-mssql
          versionString: ""
        test:
          app: nodejs/node-postgres
          versionString: ""
        test:
          app: nodejs/vuepress
          versionString: ""
        test:
          app: nodejs/webfrontend-yarnlock
          versionString: ""
        test:
          app: nodejs/websocket
          versionString: ""
        test:
          app: php/exif-example
          versionString: ""
        test:
          app: php/gd-example
          versionString: ""
        test:
          app: php/mysqli-example
          versionString: ""
        test:
          app: php/pgsql-example
          versionString: ""
        test:
          app: php/sqlsrv-example
          versionString: ""
        test:
          app: php/twig-example
          versionString: ""
        test:
          app: php/wordpress-example
          versionString: ""
        test:
          app: php/php-fpm-config
          versionString: ""
        test:
          app: python/django-app
          versionString: ""
        test:
          app: python/flask-app
          versionString: ""
        test:
          app: python/http-server-py
          versionString: ""
        test:
          app: python/mssqlserver-sample
          versionString: ""
        test:
          app: python/postgres-sample
          versionString: ""
        test:
          app: python/shapely-flask-app
          versionString: ""
        test:
          app: ruby/Jekyll-app
          versionString: ""
        test:
          app: ruby/ruby-on-rails-app
          versionString: ""
        test:
          app: ruby/sinatra-app
          versionString: ""
        test:
          app: StaticWebAppsSamples/HugoClientDotNetCoreServer
          versionString: ""
        test:
          app: StaticWebAppsSamples/ReactClientNodeServer
          versionString: ""

    steps:
      - uses: actions/checkout@v3
        with:
          repository: microsoft/Oryx

      - name: Build application
        run: docker run --rm --env ORYX_SDK_STORAGE_BASE_URL="https://oryxsdksdev.blob.core.windows.net" -v $(pwd)/tests/SampleApps/${{ app }}:/app mcr.microsoft.com/oryx/build:github-actions-bullseye oryx build /app ${{ versionString }} --debug
