name: Bullseye SWA support testing

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        DotNetCore_HttpTriggerV3Sample:
          app: azureFunctionsApps/DotNetCore_HttpTriggerV3Sample
          versionString: ""
        DotNetCore_HttpTriggerV4Sample:
          app: azureFunctionsApps/DotNetCore_HttpTriggerV4Sample
          versionString: ""
        Node_HttpTriggerSample:
          app: azureFunctionsApps/Node_HttpTriggerSample
          versionString: ""
        Python_HttpTriggerSample:
          app: azureFunctionsApps/Python_HttpTriggerSample
          versionString: ""
        TypeScript_HttpTriggerSample:
          app: azureFunctionsApps/TypeScript_HttpTriggerSample
          versionString: ""
        NetCore6BlazorWasmApp:
          app: DotNetCore/NetCore6BlazorWasmApp
          versionString: ""
        NetCore6PreviewMvcApp:
          app: DotNetCore/NetCore6PreviewMvcApp
          versionString: ""
        NetCore7PreviewMvcApp:
          app: DotNetCore/NetCore7PreviewMvcApp
          versionString: ""
        NetCore60IsolatedApp:
          app: DotNetCore/NetCore60IsolatedApp
          versionString: ""
        NetCoreApp31.MvcApp:
          app: DotNetCore/NetCoreApp31.MvcApp
          versionString: ""
        hello-world:
          app: golang/hello-world
          versionString: ""
        hugo-sample:
          app: hugo/hugo-sample
          versionString: ""
        MavenSimpleJavaApp:
          app: java/MavenSimpleJavaApp
          versionString: ""
        angular14app:
          app: nodejs/angular14app
          versionString: ""
        create-react-app-sample:
          app: nodejs/create-react-app-sample
          versionString: ""
        helloworld-nuxtjs:
          app: nodejs/helloworld-nuxtjs
          versionString: ""
        monorepo-lerna-npm:
          app: nodejs/monorepo-lerna-npm
          versionString: ""
        nextjs-yarn2-example:
          app: nodejs/nextjs-yarn2-example
          versionString: ""
        NodeAndTypeScriptHelloWorld:
          app: nodejs/NodeAndTypeScriptHelloWorld
          versionString: ""
        node-mssql:
          app: nodejs/node-mssql
          versionString: ""
        node-postgres:
          app: nodejs/node-postgres
          versionString: ""
        vuepress:
          app: nodejs/vuepress
          versionString: ""
        webfrontend-yarnlock:
          app: nodejs/webfrontend-yarnlock
          versionString: ""
        websocket:
          app: nodejs/websocket
          versionString: ""
        exif-example:
          app: php/exif-example
          versionString: ""
        gd-example:
          app: php/gd-example
          versionString: ""
        mysqli-example:
          app: php/mysqli-example
          versionString: ""
        pgsql-example:
          app: php/pgsql-example
          versionString: ""
        sqlsrv-example:
          app: php/sqlsrv-example
          versionString: ""
        twig-example:
          app: php/twig-example
          versionString: ""
        wordpress-example:
          app: php/wordpress-example
          versionString: ""
        php-fpm-config:
          app: php/php-fpm-config
          versionString: ""
        django-app:
          app: python/django-app
          versionString: ""
        flask-app:
          app: python/flask-app
          versionString: ""
        http-server-py:
          app: python/http-server-py
          versionString: ""
        mssqlserver-sample:
          app: python/mssqlserver-sample
          versionString: ""
        postgres-sample:
          app: python/postgres-sample
          versionString: ""
        shapely-flask-app:
          app: python/shapely-flask-app
          versionString: ""
        Jekyll-app:
          app: ruby/Jekyll-app
          versionString: ""
        ruby-on-rails-app:
          app: ruby/ruby-on-rails-app
          versionString: ""
        sinatra-app:
          app: ruby/sinatra-app
          versionString: ""
        HugoClientDotNetCoreServer:
          app: StaticWebAppsSamples/HugoClientDotNetCoreServer
          versionString: ""
        ReactClientNodeServer:
          app: StaticWebAppsSamples/ReactClientNodeServer
          versionString: ""

    steps:
      - uses: actions/checkout@v3
        with:
          repository: microsoft/Oryx

      - name: Build application
        run: docker run --rm --env ORYX_SDK_STORAGE_BASE_URL="https://oryxsdksdev.blob.core.windows.net" -v $(pwd)/tests/SampleApps/${{ app }}:/app mcr.microsoft.com/oryx/build:github-actions-bullseye oryx build /app ${{ versionString }} --debug
