name: python.h error test

on:
  push:
    branches:
      - 'main'  
  workflow_dispatch:

jobs:
  # regex:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       app:
  #         - python/django-regex-example-app
  #       version: 
  #         - 3.7.15
  #         - 3.7.16
  #         - 3.8.15
  #         - 3.8.16
  #         - 3.9.15
  #         - 3.9.16
  #         - 3.10.4
  #         - 3.10.8
  #         - 3.10.9
  #         - 3.11.1
  #       buildImage:
  #         - mcr.microsoft.com/oryx/build:github-actions-debian-buster-20230124.1
  #         - mcr.microsoft.com/oryx/build:github-actions-debian-bullseye-20230124.1
  #       storageAccount:
  #         - "ORYX_SDK_STORAGE_BASE_URL=https://oryxsdkssandbox.blob.core.windows.net"

  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         repository: microsoft/Oryx # regex requirements.txt

  #     - name: Build application - ${{ matrix.app }} - ${{ matrix.version }} - ${{ matrix.buildImage }}
  #       run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app ${{ matrix.buildImage }} oryx build /app --platform python --platform-version ${{ matrix.version }} --property ${{ matrix.storageAccount }}

  cffi:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        app:
          - python/django-regex-example-app
        version: 
          - 3.7.15
          - 3.7.16
          - 3.8.12
          - 3.8.15
          - 3.8.16
          - 3.9.7
          - 3.9.15
          - 3.9.16
          - 3.10.4
          - 3.10.8
          - 3.10.9
          - 3.11.0
          - 3.11.1 
        buildImageTag:
          - github-actions-20220805.1
          - github-actions-buster-20220805.1
          - github-actions-bullseye-20220805.1
          - github-actions-debian-stretch-20230130.1
          - github-actions-debian-buster-20230130.1
          - github-actions-debian-bullseye-20230130.1
        storageAccount:
          - "ORYX_SDK_STORAGE_BASE_URL=https://oryxsdkssandbox.blob.core.windows.net"

    steps:
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2.0.0
        with: 
         registry: mcr.microsoft.com
      - uses: actions/checkout@v3
        with:
          repository: microsoft/Oryx
          ref: pauld/test-pythonh  # partner requirements.txt

      - name: Build application - ${{ matrix.version }} - ${{ matrix.buildImageTag }}
        run: docker run --rm -e ${{ matrix.storageAccount }} -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app mcr.microsoft.com/oryx/build:${{ matrix.buildImageTag }} oryx build /app --platform python --platform-version ${{ matrix.version }}
