name: SWA Test - python

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:      
        app:
          - python/django-app
          - python/flask-app
          - python/http-server-py
          - python/mssqlserver-sample
          - python/postgres-sample
          - python/shapely-flask-app
        versionString: 
          - "--platform python --platform-version 3.8"
          - "--platform python --platform-version 3.9"
          - "--platform python --platform-version 3.10"

    steps:
      - uses: actions/checkout@v3
        with:
          repository: microsoft/Oryx

      - name: Build application
        run: docker run --rm --env ORYX_SDK_STORAGE_BASE_URL="https://oryxsdksdev.blob.core.windows.net" -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app mcr.microsoft.com/oryx/build:github-actions-bullseye oryx build /app ${{ matrix.versionString }} --debug
