name: SWA Test - dotnet

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:      
        app:
          - azureFunctionsApps/DotNetCore_HttpTriggerV3Sample
          - azureFunctionsApps/DotNetCore_HttpTriggerV4Sample
          - DotNetCore/NetCore6BlazorWasmApp
          - DotNetCore/NetCore6PreviewMvcApp
          - DotNetCore/NetCore7PreviewMvcApp
          - DotNetCore/NetCore60IsolatedApp
          - DotNetCore/NetCoreApp31.MvcApp
          - StaticWebAppsSamples/HugoClientDotNetCoreServer
        versionString: 
          - ""

    steps:
      - uses: actions/checkout@v3
        with:
          repository: microsoft/Oryx

      - name: Build application
        run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app mcr.microsoft.com/oryx/build:latest oryx build /app ${{ matrix.versionString }} --debug
